### Get every trips
GET {{host}}/trips

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Add a new trip
POST {{host}}/trips
Content-Type: application/json

{
  "date": "2015-10-21",
  "drivers": ["foo"],
  "passengers": [
    "bar"
  ]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Get the credits
GET {{host}}/credits

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### List the carpoolers
GET {{host}}/carpoolers

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
